### ISSUE TITLE
set up raw-addresses.txt and addresses.txt

### ISSUE THREAD

**Issue by mxito3** [tech-bureau/catapult-service-bootstrap#11]
is there an example of how to set up raw-addresses.txt and addresses.txt

**Comment by jontey** [comment]
It is generated for you when you run `docker-compose up`

**Comment by mxito3** [comment]
> It is generated for you when you run `docker-compose up`

The problem is that the container which used to generete address response with an error ' (core dumped) /catapult/bin/catapult.tools.address --generate=${num_addresses} -n mijin-test > ${raw_addresses_path}' .but i can use 'nem2-cli account generate --network MIJIN_TEST --save --url http://localhost:3000' in host . so i want to generate address outside container use nem2-cli.but the problem is i don't know the format of raw_addresses.can you give a example of raw_addresses?

**Comment by jontey** [comment]
This is what I get when I generate the addresses. (Private keys are redacted because they are private)
```
Address Tool
Copyright (c) Jaguar0625, gimre, BloodyRookie, Tech Bureau, Corp.
catapult version: 0.2.0.2 (public)

Address Tool Initializing Logging...

--- generating 2 keys ---
           private key: <private key>
            public key: 151B942D755F50B540BC70D2F80560828F47DCE2FF4170AE7D929C8938F8A7C8
  address (mijin-test): SDS52FRHN7Z74ZG4WFR27HOJNQDASNL2GM2EIGIX

           private key: <private key>
            public key: F855C55F76A36B48D449396F5E9474548638CCCB9B15EE49884CC8C39E5B28F0
  address (mijin-test): SAJOPVZJOUHKYSIRIKWODLITHVTN4PLVMREAVM3V

```

**Comment by jontey** [comment]
@mxito3 did this help?

I think this issue is closed.

**Comment by mxito3** [comment]
> @mxito3 did this help?
> 
> I think this issue is closed.

someone generate these two files,it works！
