### ISSUE TITLE
catapult-service-bootstrap_api-node-0_1_990d4c344cac exited with code 254

### ISSUE THREAD

**Issue by mxito3** [tech-bureau/catapult-service-bootstrap#12]
![image](https://user-images.githubusercontent.com/25946298/49373970-e1027a80-f73a-11e8-845b-f551fb992269.png)
as soon as i send a transaction,the api node will shut down,when i restart it, it said that file.lock can't access,so i delete file.lock,but i get this error.what should i do ?

**Comment by gigonzalezs** [comment]
I have the same problem, after send a transfer the API node exits. I Attached the log of all containers
[log.txt](https://github.com/tech-bureau/catapult-service-bootstrap/files/2673756/log.txt)

**Comment by gigonzalezs** [comment]
returning to commit 44b32b7e1875af45a73c25b6829dc32efc345de9 (july 2018) works fine

**Comment by ags-21ct** [comment]
me too 

this my log 
[log.txt](https://github.com/tech-bureau/catapult-service-bootstrap/files/2674421/log.txt)

**Comment by kaiyzen** [comment]
@mxito3 please try pull from latest master commits, we found an errant config setting on api node when merging in latest config templates for the bison release

**Comment by gigonzalezs** [comment]
thanks @kaiyzen it's works. @mxito3 can you close the issue?
