### ISSUE TITLE
Ubuntu 18: not work

### ISSUE THREAD

**Issue by vlad-bondarenko** [tech-bureau/catapult-service-bootstrap#14]
Attaching to catapult-service-bootstrap_generate-configs_1_4c6d301a3db5, catapult-service-bootstrap_generate-raw-addresses_1_4d9da108c744, catapult-service-bootstrap_db_1_c3b75c16c8e7, catapult-service-bootstrap_peer-node-0-nemgen_1_186962e182ad, catapult-service-bootstrap_store-addresses_1_70db91352842, catapult-service-bootstrap_peer-node-1-nemgen_1_33228522587f, catapult-service-bootstrap_api-node-0-nemgen_1_3d35982f9898, catapult-service-bootstrap_peer-node-0_1_f56204908c9b, catapult-service-bootstrap_api-node-0_1_bc14bff0a03d, catapult-service-bootstrap_init-db_1_1c6c53646be7, catapult-service-bootstrap_peer-node-1_1_7d32778f7113, catapult-service-bootstrap_rest-gateway_1_120c20cbb5bb
generate-raw-addresses_1_4d9da108c744 | /bin-mount/generate-raw-addresses-if-needed: line 8:     8 Illegal instruction     (core dumped) /catapult/bin/catapult.tools.address --generate=${num_addresses} -n mijin-test > ${raw_addresses_path}
db_1_c3b75c16c8e7         | 2018-12-29T18:52:25.697+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
catapult-service-bootstrap_generate-raw-addresses_1_4d9da108c744 exited with code 132

**Comment by cfcodefans** [comment]
yes, encountered the same problem with catapult-server:gcc-0.2.0.2,
 it just shows "core dump" without further info

catapult-server:gcc-0.1.0.2 works fine

**Comment by vlad-bondarenko** [comment]
rest-gateway_1_120c20cbb5bb | 2019-01-03T11:45:14.609Z - verbose: connected to mongo at mongodb://db:27017/catapult
rest-gateway_1_120c20cbb5bb | 2019-01-03T11:45:14.611Z - info: registering routes
rest-gateway_1_120c20cbb5bb | 2019-01-03T11:45:14.668Z - info: listening on port 3000
catapult-service-bootstrap_peer-node-0_1_f56204908c9b exited with code 132
api-node-0_1_bc14bff0a03d | total 12K
api-node-0_1_bc14bff0a03d | drwxr-xr-x 3 root root 4.0K Jan  3 11:45 .
api-node-0_1_bc14bff0a03d | drwxr-xr-x 1 root root 4.0K Dec 29 09:22 ..
api-node-0_1_bc14bff0a03d | drwxr-xr-x 2 root root 4.0K Jan  3 11:45 00000
catapult-service-bootstrap_api-node-0_1_bc14bff0a03d exited with code 132
peer-node-1_1_7d32778f7113 | total 12K
peer-node-1_1_7d32778f7113 | drwxr-xr-x 3 root root 4.0K Jan  3 11:45 .
peer-node-1_1_7d32778f7113 | drwxr-xr-x 1 root root 4.0K Dec 29 09:22 ..
peer-node-1_1_7d32778f7113 | drwxr-xr-x 2 root root 4.0K Jan  3 11:45 00000
catapult-service-bootstrap_peer-node-1_1_7d32778f7113 exited with code 132

Exec command:
curl localhost:3000/block/1
Result:
b_1_c3b75c16c8e7         | 2019-01-03T11:45:39.081+0000 I NETWORK  [listener] connection accepted from 172.18.0.6:56738 #2 (2 connections now open)
rest-gateway_1_120c20cbb5bb | 2019-01-03T11:45:39.084Z - error: caught error 500 
rest-gateway_1_120c20cbb5bb | { message: 'Cannot read property \'height\' of undefined',
rest-gateway_1_120c20cbb5bb |   jse_shortmsg: 'Cannot read property \'height\' of undefined',
rest-gateway_1_120c20cbb5bb |   jse_cause: {},
rest-gateway_1_120c20cbb5bb |   jse_info: {},
rest-gateway_1_120c20cbb5bb |   stack: 'InternalError: Cannot read property \'height\' of undefined\n    at Object.toRestError (/node_modules/catapult-api-rest/_build/server/errors.js:31:5)\n    at toRestError (/node_modules/catapult-api-rest/_build/server/bootstrapper.js:33:27)\n    at result.catch.err (/node_modules/catapult-api-rest/_build/server/bootstrapper.js:130:13)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)',
rest-gateway_1_120c20cbb5bb |   body: 
rest-gateway_1_120c20cbb5bb |    { code: 'Internal',
rest-gateway_1_120c20cbb5bb |      message: 'Cannot read property \'height\' of undefined' } }

**Comment by jontey** [comment]
@cfcodefans may I know what are the hardware specs you are running?

**Comment by cfcodefans** [comment]
@jontey 
sure

processor       : 23
vendor_id       : GenuineIntel
cpu family      : 6
model           : 44
model name      : Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz
stepping        : 2
microcode       : 0x15
cpu MHz         : 2925.950
cache size      : 12288 KB

$ free -g
              total        used        free      shared  buff/cache   available
Mem:            125          21          14           0          88          99

the weird part is, I ran catapult-server:gcc-0.1.0.2 on this server before, it ran alright
I cloned and ran catapult-server:gcc-0.2.0.2 on the same server, it failed with "core dump".
` /bin-mount/generate-raw-addresses-if-needed: line 8:     7 Illegal instruction     (core dumped) /catapult/bin/catapult.tools.address --generate=${num_addresses} -n mijin-test > ${raw_addresses_path}
`

I ran it on another clean server without any catapult docker images before, it started alright.
hope this info can help.

**Comment by jontey** [comment]
I had that issue as well with 0.2.0.2, but only on the node running a Celeron processor. The node running a i5 processor (can't remember the specs) ran without any issue. Compiled a docker image from scratch on the Celeron node and it runs fine. 

I haven't had the chance to upload the docker image to docker hub yet but you could compile it yourself to see if it works https://github.com/luxtagofficial/catapult-server. Just skip to the `Compiling catapult` section. After the build completes, replace `catapult-server:gcc-0.2.0.2` with `nem-catapult:latest` in the `docker-compose.yml` file. 

***Update***
Uploaded the image on docker hub. You can find it here https://hub.docker.com/r/luxtagofficial/catapult-server with the tag `0.2.0.2`. It replaces both `catapult-server` and `catapult-tools`
