### ISSUE TITLE
after run bootstrap 2 week2 it not work

### ISSUE THREAD

**Issue by athlona64** [tech-bureau/catapult-service-bootstrap#16]
i can't send transaction via nem2-sdk always show 503 error

it was work about 2 weeks

[logsnem.txt](https://github.com/tech-bureau/catapult-service-bootstrap/files/2729321/logsnem.txt)

**Comment by planethouki** [comment]
should start api-node-0
```
rm data/api-node-0/file.lock
docker-compose start api-node-0
```

**Comment by athlona64** [comment]
still won't work

**Comment by kaiyzen** [comment]
seems like this might have been issue with api node failing, in pre 0.4 versions recovery on api nodes on a failure wasnt gauranteed due to possible data getting in a bad state, if you see this happen in 0.5+ please open another issue and report in the slack
