### ISSUE TITLE
can't call api via nem2-sdk and CLI

### ISSUE THREAD

**Issue by athlona64** [tech-bureau/catapult-service-bootstrap#17]
code: 'ENOTFOUND',
rest-gateway_1            |   errno: 'ENOTFOUND',
rest-gateway_1            |   syscall: 'getaddrinfo',
rest-gateway_1            |   hostname: 'api-node-0',
rest-gateway_1            |   host: 'api-node-0',
rest-gateway_1            |   port: 7900 }
rest-gateway_1            | 2019-01-07T03:35:10.948Z - error: caught error 503 
rest-gateway_1            | { message: 'connection failed',
rest-gateway_1            |   jse_shortmsg: 'connection failed',
rest-gateway_1            |   jse_info: {},
rest-gateway_1            |   stack: 'ServiceUnavailableError: connection failed\n    at Object.createServiceUnavailableError (/node_modules/catapult-api-rest/_build/server/errors.js:55:44)\n    at Socket.serverSocket.on.on (/node_modules/catapult-api-rest/_build/connection/connectionService.js:65:19)\n    at emitOne (events.js:120:20)\n    at Socket.emit (events.js:210:7)\n    at TCP._handle.close [as _onclose] (net.js:547:12)',

CLI

root@ip-172-31-26-96:~/catapult-service-bootstrap# nem2-cli transaction transfer --recipient SAY4ZV-727RNC-CCZZZN-R5QUPE-U4OLBX-CD3L4O-J2PZ --message "payout of 10000 LIKE" --mosaics cyphermines:like::10
Error {"code":"ServiceUnavailable","message":"connection failed"}

it was work but now can't

show above error

**Comment by tmyi** [comment]
I'm facing the same problem.

rest-gateway_1            | 2019-05-01T15:04:19.307Z - verbose: connecting to api-node-0:7900
rest-gateway_1            | 2019-05-01T15:04:19.346Z - verbose: error raised by api-node-0:7900 connection 
rest-gateway_1            | { message: 'getaddrinfo ENOTFOUND api-node-0 api-node-0:7900',
rest-gateway_1            |   stack: 'Error: getaddrinfo ENOTFOUND api-node-0 api-node-0:7900\n    at errnoException (dns.js:53:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)',
rest-gateway_1            |   code: 'ENOTFOUND',
rest-gateway_1            |   errno: 'ENOTFOUND',
rest-gateway_1            |   syscall: 'getaddrinfo',
rest-gateway_1            |   hostname: 'api-node-0',
rest-gateway_1            |   host: 'api-node-0',
rest-gateway_1            |   port: 7900 }
rest-gateway_1            | 2019-05-01T15:04:19.347Z - error: caught error 503 
rest-gateway_1            | { message: 'connection failed',
rest-gateway_1            |   jse_shortmsg: 'connection failed',
rest-gateway_1            |   jse_info: {},
rest-gateway_1            |   stack: 'ServiceUnavailableError: connection failed\n    at Object.createServiceUnavailableError (/node_modules/catapult-api-rest/_build/server/errors.js:55:44)\n    at Socket.serverSocket.on.on (/node_modules/catapult-api-rest/_build/connection/connectionService.js:65:19)\n    at emitOne (events.js:120:20)\n    at Socket.emit (events.js:210:7)\n    at TCP._handle.close [as _onclose] (net.js:547:12)',
rest-gateway_1            |   body: { code: 'ServiceUnavailable', message: 'connection failed' } }

CLI

$ nem2-cli transaction mosaic --amount 1000000 --supplymutable --divisibility 0 --duration 1000
Do you want mosaic to be transferable? [y/n]: n
Do you want mosaic to have levy mutable? [y/n]: n
Error {"code":"ServiceUnavailable","message":"connection failed"}
