### ISSUE TITLE
Question about emacs dependence

### ISSUE THREAD

**Issue by mijiturka** [tech-bureau/catapult-service-bootstrap#18]
The store-addresses and generate-configs containers built from the ruby-alpine Dockerfile [install emacs-nox in the container](https://github.com/tech-bureau/catapult-service-bootstrap/blob/2348d319e16f89805b64c3987f405f82cf1805f0/dockerfiles/ruby-alpine/Dockerfile#L4). Is there a requirement for this beyond convenience for a user who runs a console on them? 

I couldn't find a call to it anywhere, or notice any difference when removing it from the list of things to install; but I'd like to know if I'm missing something more subtle.

Apologies if this is not the right place to ask questions, and thanks for your work on this project, it's a very convenient starting point for setting up Catapult!

**Comment by kaiyzen** [comment]
dev who leads the project uses emacs so convenient to have it in there

would ask questions like this on the slack group under #sig-testing
