### ISSUE TITLE
Docker-compose up. Build index done scanned 0 total records. 0 secs

### ISSUE THREAD

**Issue by drewfrost** [tech-bureau/catapult-service-bootstrap#19]
<img width="1227" alt="2019-01-07 16 05 58" src="https://user-images.githubusercontent.com/22340615/50772359-282ddf00-1296-11e9-81a9-b0b082fac056.png">
I have issues launching catapult. After compose i receive "Build index done scanned 0 total records. 0 secs" and there is no answer from server. Tried docker system prune -a --volumes and totally reinstalling docker but it made no difference.

**Comment by jontey** [comment]
I think this is similar to #21
