### ISSUE TITLE
failed to register new namespace from java sdk

### ISSUE THREAD

**Issue by cfcodefans** [tech-bureau/catapult-service-bootstrap#22]
using io.nem.sdk.model.transaction.RegisterNamespaceTransaction#createRootNamespace
in io.nem:sdk:0.9.1 (there is not any new updates in [java sdk](https://github.com/nemtech/nem2-sdk-java) with catapult version 0.3.0

got error Failure_Namespace_Name_Id_Mismatch, 
This is not documented in 
http://beta.catapult.mijin.io/docs/api/errors.html

after roughly checking some source code, I guess the issue is mismatch between
io.nem.sdk.model.transaction.IdGenerator#generateId
```java
public static BigInteger generateId(String name, BigInteger parentId) {
        byte[] parentIdBytes = new byte[8];
        ByteBuffer.wrap(parentIdBytes).put(parentId.toByteArray()); // GO
        ArrayUtils.reverse(parentIdBytes);

        byte[] bytes = name.getBytes();

        byte[] result = Hashes.sha3_256(parentIdBytes, bytes);
        byte[] low = Arrays.copyOfRange(result, 0, 4);
        byte[] high = Arrays.copyOfRange(result, 4, 8);
        ArrayUtils.reverse(low);
        ArrayUtils.reverse(high);

        byte[] last = ArrayUtils.addAll(high, low);

        return new BigInteger(last);
    }
```

and 
https://github.com/nemtech/catapult-server/blob/master/plugins/txes/namespace/src/model/NamespaceIdGenerator.cpp
```cpp
NamespaceId GenerateNamespaceId(NamespaceId parentId, const RawString& name) noexcept {
		Hash256 result;
		crypto::Sha3_256_Builder sha3;
		sha3.update({
			{ reinterpret_cast<const uint8_t*>(&parentId), sizeof(NamespaceId) },
			{ reinterpret_cast<const uint8_t*>(name.pData), name.Size }
		});
		sha3.final(result);

		// set high bit
		constexpr uint64_t Namespace_Flag = 1ull << 63;
		return NamespaceId(reinterpret_cast<const uint64_t&>(*result.data()) | Namespace_Flag);
	}
```

same java code works fine with version 0.1.0

should I post this error to [java sdk](https://github.com/nemtech/nem2-sdk-java) repository?

**Comment by jontey** [comment]
Try using this branch https://github.com/nemtech/nem2-sdk-java/tree/cow-base/master

There has been breaking changes in mosaics/namespace structure in the catapult cow release
