### ISSUE TITLE
can not start the verstion 0.5.0.1

### ISSUE THREAD

**Issue by cfcodefans** [tech-bureau/catapult-service-bootstrap#24]
./cmds/setup-network
Pulling generate-raw-addresses (techbureau/catapult-tools-private:gcc-master-e232da9c76)...
ERROR: pull access denied for techbureau/catapult-tools-private, repository does not exist or may require 'docker login'

`techbureau/catapult-tools-private` seems to be inaccessible

**Comment by dl-nice** [comment]
techbureau/catapult-tools:gcc-0.5.0.1

**Comment by kaiyzen** [comment]
errant ref to old test image as DLnice points out above the gcc-0.5.0.1 ref is correct for the release, its updated in latest commit/tag for 0.5

**Comment by kaiyzen** [comment]
sans update/reply assuming this works now with last fix, closing out, if still persists open a new one and/or post on #sig-testing in the slack group
