### ISSUE TITLE
can't start catapult-service-bootstrap 0.5

### ISSUE THREAD

**Issue by dgarcia360** [tech-bureau/catapult-service-bootstrap#25]
**Description of the error**

After executing the readme instructions to run the network, I get the following error:

```
Creating network "docker_default" with the default driver
ERROR: No such service:
```
**Reproducing the error**

1. Clone the repo.
2. ./cmds/start-all

**System info**
* Ubunutu 18.04.2 LTS
* Docker version 18.09.2
* docker-compose version 1.22.0

**Comment by dl-nice** [comment]
He shouldn't have explained it clearly.I think it should be configurable.

**Comment by mijinc0** [comment]
Greetings.

I got same error. This is because docker-compose up option contains double quotes.

`start-all`

```
# last line
docker-compose -f cmds/docker/docker-compose.yml up "$daemon_flag" "$build_flag"
```

So, If double quotation is not necessary regardless of the environment, it seems better to have no double quotation.

```
# delete double quotation
docker-compose -f cmds/docker/docker-compose.yml up $daemon_flag $build_flag
```

### system info

Ubuntu 18.04.2  LTS
Docker version 18.09.6    
docker-compose version 1.21.2

**Comment by dgarcia360** [comment]
Thanks @mijinc0 ,
I have tried adding the flag "-b" to the command, and it also works:

`./cmds/start-all -b -d`

However, I'm not sure if it is the proper way to start up the service.

**Comment by mijinc0** [comment]
I am not professional of shell-script, but I understand that `-b` is converted into `--build` in `start-all`, and `--build` is option of `docker-compose`. 

`start-all` just execute `docker-compose -f cmds/docker/docker-compose.yml up`, so If you need `--build` option, you should use `-b` when you execute `start-all`.

`--build` option will try to build images before starting containers regardless of existing images. So, I think `--build` is not nessesary for normal use.

**use `-b` option**
docker-compose -f cmds/docker/docker-compose.yml up --build

For this error, I think you can know what is happening with the following command.

```
$ sudo docker-compose -f cmds/docker/docker-compose.yml up ""
```

**Comment by kaiyzen** [comment]
pushed some updates, can you guys test out on latest to see if behavior is fixed up

**Comment by dgarcia360** [comment]
It is working fine! Closing the issue.
