### ISSUE TITLE
v0.3.0 is dragon or cow network?

### ISSUE THREAD

**Issue by 1nfinite** [tech-bureau/catapult-service-bootstrap#27]
Hello, may i know that v0.3.0 is which network. I can't send transaction with nem2-cli 0.12 and nem2-sdk 0.12.3. What is the compatible version of nem2-cli and nem2-sdk for 0.3.0?

And where can i find v0.4.0?

**Comment by kaiyzen** [comment]
there is no 0.4 for bootstrap, there was an issue with running networks on smaller hosts with 2 or less cpu's.  that issue was fixed with the 0.5 build, that should be used going forward until the next release
