### ISSUE TITLE
Unable to find image 'dockerfiles/ruby-alpine:latest'

### ISSUE THREAD

**Issue by scopichol** [tech-bureau/catapult-service-bootstrap#5]
Unable to find image 'dockerfiles/ruby-alpine:latest' locally
Error response from daemon: Get https://registry-1.docker.io/v2/dockerfiles/ruby-alpine/manifests/latest: unauthorized: incorrect username or password.

**Comment by kaiyzen** [comment]
assuming this is out of date and non issue, havent seen this reported anywhere else so maybe intermitent issue
