### ISSUE TITLE
Unable to use docker compose up

### ISSUE THREAD

**Issue by thomas-tran** [tech-bureau/catapult-service-bootstrap#6]
I tried to run docker on windows 10 and got the following error 
b_1                      | -----  END BACKTRACE  -----
peer-node-1-nemgen_1      | bash: /bin-mount/wait: /bin/bash^M: bad interpreter:                                           No such file or directory
catapult-service-bootstrap_generate-raw-addresses_1 exited with code 126
api-node-0_1              | bash: /bin-mount/wait: /bin/bash^M: bad interpreter:                                           No such file or directory
init-db_1                 | sleep: invalid time interval '1\r'
init-db_1                 | Try 'sleep --help' for more information.
: invalid option          | /userconfig/mongors.sh: line 2: set: -
init-db_1                 | set: usage: set [-abefhkmnptuvxBCHP] [-o option-name                                          ] [--] [arg ...]
init-db_1                 | /userconfig/mongors.sh: line 3: $'\r': command not f                                          ound
init-db_1                 | /userconfig/mongors.sh: line 26: syntax error: unexp                                          ected end of file
peer-node-1_1             | bash: /bin-mount/wait: /bin/bash^M: bad interpreter:                                           No such file or directory
catapult-service-bootstrap_peer-node-0-nemgen_1 exited with code 126
catapult-service-bootstrap_api-node-0-nemgen_1 exited with code 126
catapult-service-bootstrap_db_1 exited with code 14
peer-node-0_1             | bash: /bin-mount/wait: /bin/bash^M: bad interpreter:                                           No such file or directory
rest-gateway_1            | ash: /bin-mount/wait: not found
catapult-service-bootstrap_peer-node-1-nemgen_1 exited with code 126
catapult-service-bootstrap_peer-node-1_1 exited with code 126
catapult-service-bootstrap_api-node-0_1 exited with code 126
catapult-service-bootstrap_init-db_1 exited with code 2
catapult-service-bootstrap_peer-node-0_1 exited with code 126
catapult-service-bootstrap_rest-gateway_1 exited with code 127

ttran@DESKTOP-BB9UN5J MINGW64 /f/Works/proximax-storage/catapult-service-bootstr                                          ap (master)
$ init-db_1                 | set: usage: set [-abefhkmnptuvxBCHP] [-o option-na                                          me] [--] [arg ...]
init-db_1                 | /userconfig/mongors.sh: line 26: syntax error: unexp                                          ected end of file
peer-node-1_1             | bash: /bin-mount/wait: /bin/bash^M: bad interpreter:                                           No such file or directory
catapult-service-bootstrap_peer-node-0-nemgen_1 exited with code 126
catapult-service-bootstrap_api-node-0-nemgen_1 exited with code 126
catapult-service-bootstrap_db_1 exited with code 14
peer-node-0_1             | bash: /bin-mount/wait: /bin/bash^M: bad interpreter:                                           No such file or directory
rest-gateway_1            | ash: /bin-mount/wait: not found
catapult-service-bootstrap_peer-node-1-nemgen_1 exited with code 126
catapult-service-bootstrap_peer-node-1_1 exited with code 126
catapult-service-bootstrap_api-node-0_1 exited with code 126
catapult-service-bootstrap_init-db_1 exited with code 2
catapult-service-bootstrap_peer-node-0_1 exited with code 126
catapult-service-bootstrap_rest-gateway_1 exited with code 127
bash: init-db_1: command not found

**Comment by jontey** [comment]
This has to do with how git checkout works on Windows. The default is to checkout with Window line endings. You'll need to change it to checkout as-is

Use this to change the global git setting

```
git config --global core.autocrlf false
```

Source: https://stackoverflow.com/a/13154031

**Comment by thomas-tran** [comment]
It did not work. More error

 failed to connect to server [db:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND db db:27017]
rest-gateway_1            |     at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:505:11)
rest-gateway_1            |     at emitOne (events.js:115:13)
rest-gateway_1            |     at Pool.emit (events.js:210:7)
rest-gateway_1            |     at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:329:12)
rest-gateway_1            |     at Object.onceWrapper (events.js:318:30)
rest-gateway_1            |     at emitTwo (events.js:125:13)
rest-gateway_1            |     at Connection.emit (events.js:213:7)
rest-gateway_1            |     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:245:50)
rest-gateway_1            |     at Object.onceWrapper (events.js:316:30)
rest-gateway_1            |     at emitOne (events.js:115:13)
rest-gateway_1            | 2018-08-30T09:32:27.669Z - error: rest server is exiting due to error MongoNetworkError: failed to connect to server [db:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND db db:27017]
rest-gateway_1            |     at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:505:11)
rest-gateway_1            |     at emitOne (events.js:115:13)
rest-gateway_1            |     at Pool.emit (events.js:210:7)
rest-gateway_1            |     at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:329:12)
rest-gateway_1            |     at Object.onceWrapper (events.js:318:30)
rest-gateway_1            |     at emitTwo (events.js:125:13)
rest-gateway_1            |     at Connection.emit (events.js:213:7)
rest-gateway_1            |     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:245:50)
rest-gateway_1            |     at Object.onceWrapper (events.js:316:30)
rest-gateway_1            |     at emitOne (events.js:115:13)

**Comment by jontey** [comment]
did you make any changes to the docker-compose?

**Comment by thomas-tran** [comment]
However, I did not make any change to the docker compose file. Just clone the source and run the docker compose on windows 10 (linux container). 

I tested with Ubuntu and Mac and it worked fine.

**Comment by jontey** [comment]
Are you using dockertoolbox on windows or native windows docker installation?

**Comment by thomas-tran** [comment]
The native docker for windows

**Comment by jontey** [comment]
Ok. I'm not too familiar with it. Sorry about that.

**Comment by Boohi** [comment]
> This has to do with how git checkout works on Windows. The default is to checkout with Window line endings. You'll need to change it to checkout as-is
> 
> Use this to change the global git setting
> 
> ```
> git config --global core.autocrlf false
> ```
> Source: https://stackoverflow.com/a/13154031

This did not work for me either. Still getting the same error after git config change

**Comment by jontey** [comment]
Did you delete the folder and check out the repository after you change the settings?+

**Comment by efelipe402** [comment]
Hello How is it going!

I'm on Windows 8, with Docker version 18.03.0-ce, build 0520e24302  and   docker-compose version 1.20.1, build 5d8c71b2  does not work,.
Even I installed the mongoDBserver on the machine, and ran git config --global core.autocrlf false command.

But does not start the service.

any comment, thank you for your time!

**Comment by honeynatividad** [comment]
> Hello How is it going!
> 
> I'm on Windows 8, with Docker version 18.03.0-ce, build 0520e24302 and docker-compose version 1.20.1, build 5d8c71b2 does not work,.
> Even I installed the mongoDBserver on the machine, and ran git config --global core.autocrlf false command.
> 
> But does not start the service.
> 
> any comment, thank you for your time!

same here. im using windows 10 home edition.. cant run docker-compose up successfully.

**Comment by jontey** [comment]
@efelipe402 @honeynatividad Would each of you mind opening a new issue? This issue is already closed and the problem stated here is different from you guys
