### ISSUE TITLE
Encounter this problem after compose up

### ISSUE THREAD

**Issue by izuddinasr** [tech-bureau/catapult-service-bootstrap#7]
![error_docker-compose](https://user-images.githubusercontent.com/32283119/45995752-fa989d80-c0cb-11e8-84c5-fd184cd14060.PNG)

How to solve this problem?any idea...

**Comment by dexterslabor** [comment]
Are you on Windows? It looks like your docker service cannot mount a system folder, where among others, it will store the private-keys of pre-loaded accounts. I do not have a Windows machine, but I can recall a setting in the docker preferences to enable mounting folders.

**Comment by jontey** [comment]
This --> https://github.com/tech-bureau/catapult-service-bootstrap/issues/6#issuecomment-416976156

**Comment by honeynatividad** [comment]
![error](https://user-images.githubusercontent.com/4597060/48319093-3f5ca180-e644-11e8-86e8-508e9fd785cc.jpg)

do yo have any ideas guys what's causing this? thank you

**Comment by ImranNZ** [comment]
Getting the same, fresh Docker install on Windows 10

![image](https://user-images.githubusercontent.com/3803838/48334209-b767ad80-e6be-11e8-99f4-16ed7e988bc1.png)

**Comment by mxito3** [comment]
![image](https://user-images.githubusercontent.com/25946298/49065851-3ed62480-f25a-11e8-8984-03e02803cf81.png)
is this normal? why after 'curl localhost:3000/block/1' i got 'curl: (56) Recv failure: Connection reset by peer' error?
